CREATE DATABASE bchat_users;
USE bchat_users;

CREATE TABLE USER (
	UserID INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Role VARCHAR(100) NOT NULL,
    Biography VARCHAR(150),
    ProfilePicture VARCHAR(200),
    UserNickName VARCHAR(100)
);
CREATE TABLE REMINDER (
    ReminderID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    Completed BOOLEAN NOT NULL,
    Keyword VARCHAR(100),
    Banner VARCHAR(300),
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);
CREATE TABLE FRIEND (
    FriendID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    FriendUserID INT,
    FriendAccepted BOOLEAN,
    FOREIGN KEY (UserID) REFERENCES USER(UserID),
    FOREIGN KEY (FriendUserID) REFERENCES USER(UserID)
);
CREATE TABLE POST (
    PostID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(150),
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES USER(UserID),
    Picture VARCHAR(200),
    TimePosted DATETIME NOT NULL
);
CREATE TABLE COMMENT (
    CommentID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES USER(UserID),
    PostID INT,
    FOREIGN KEY (PostID) REFERENCES POST(PostID)
);
CREATE TABLE CHAT (
    ChatID INT AUTO_INCREMENT PRIMARY KEY,
    UserOneID INT,
    UserTwoID INT,
    FOREIGN KEY (UserOneID) REFERENCES USER(UserID),
    FOREIGN KEY (UserTwoID) REFERENCES USER(UserID),
    DateSent DATETIME NOT NULL
);