CREATE DATABASE bchat_users;
USE bchat_users;

CREATE TABLE USER (
	UserID INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Role VARCHAR(100) NOT NULL
);
CREATE TABLE REMINDER (
    ReminderID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    Completed BOOLEAN NOT NULL,
    Keyword VARCHAR(100),
    Banner VARCHAR(200),
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);